"use client";

import { useState, useMemo } from "react";
import {
    Cpu,
    Sparkles,
    Wand2,
    Zap,
    TrendingUp,
    Layers,
    Target,
    Globe,
    Search,
    BookOpen,
    BarChart3,
    CheckCircle2,
    AlertCircle,
    Settings,
    Plus,
    Trash2,
    DollarSign,
    Box,
    ShoppingCart,
    Palette,
    FileText,
    Image as ImageIcon,
    Shirt,
    Frame,
    ArrowUpRight,
    ArrowDownRight
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

interface ProductPlatform {
    name: string;
    earnings: number;
}

interface DigitalProduct {
    id: string;
    type: string;
    title: string;
    description: string;
    platforms: ProductPlatform[];
    totalEarnings: number;
    createdAt: string;
}

const PRODUCT_TYPES = [
    { id: "kdp-color-book", name: "KDP Color Book", icon: <BookOpen size={18} />, color: "text-blue-400", bg: "bg-blue-500/10" },
    { id: "poster-digital", name: "Poster Digital", icon: <ImageIcon size={18} />, color: "text-emerald-400", bg: "bg-emerald-500/10" },
    { id: "patterns", name: "Patrones para Ropa", icon: <Shirt size={18} />, color: "text-purple-400", bg: "bg-purple-500/10" },
    { id: "printable-frames", name: "Cuadros Imprimibles", icon: <Frame size={18} />, color: "text-rose-400", bg: "bg-rose-500/10" }
];

const PLATFORMS = ["Amazon KDP", "Etsy", "Printify", "Creative Fabrica"];

export function KdpFactoryApp() {
    const [products, setProducts] = useState<DigitalProduct[]>([
        {
            id: "prod_001",
            type: "KDP Color Book",
            title: "Ocean Wonders: Extreme Mandala",
            description: "Libro de colorear premium con 50 diseños de mandalas marinos.",
            platforms: [
                { name: "Amazon KDP", earnings: 450.20 },
                { name: "Etsy", earnings: 120.50 }
            ],
            totalEarnings: 570.70,
            createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
        },
        {
            id: "prod_002",
            type: "Poster Digital",
            title: "Cyberpunk Cityscape Vol.1",
            description: "Poster digital en alta resolución para decoración gamer.",
            platforms: [
                { name: "Etsy", earnings: 230.15 },
                { name: "Creative Fabrica", earnings: 45.00 }
            ],
            totalEarnings: 275.15,
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
        }
    ]);

    const [selectedType, setSelectedType] = useState(PRODUCT_TYPES[0].id);
    const [newTitle, setNewTitle] = useState("");
    const [newDesc, setNewDesc] = useState("");

    const stats = useMemo(() => {
        const total = products.reduce((acc, p) => acc + p.totalEarnings, 0);
        const count = products.length;
        const avg = count > 0 ? total / count : 0;
        return { total, count, avg };
    }, [products]);

    const handleAddProduct = () => {
        if (!newTitle.trim()) {
            toast.error("El título es obligatorio");
            return;
        }

        const typeInfo = PRODUCT_TYPES.find(t => t.id === selectedType);

        // Mock earnings for the new product
        const mockPlatforms = PLATFORMS.slice(0, Math.floor(Math.random() * 3) + 1).map(name => ({
            name,
            earnings: Math.floor(Math.random() * 100) + 20
        }));
        const totalEarnings = mockPlatforms.reduce((acc, p) => acc + p.earnings, 0);

        const newProduct: DigitalProduct = {
            id: `prod_${Date.now()}`,
            type: typeInfo ? typeInfo.name : "Digital Asset",
            title: newTitle.trim(),
            description: newDesc.trim() || "Generated by KDP Factory AI Engine",
            platforms: mockPlatforms,
            totalEarnings,
            createdAt: new Date().toISOString()
        };

        setProducts([newProduct, ...products]);
        setNewTitle("");
        setNewDesc("");
        toast.success("Producto digital creado con éxito");
    };

    const handleDeleteProduct = (id: string) => {
        setProducts(products.filter(p => p.id !== id));
        toast.success("Producto eliminado");
    };

    return (
        <div className="space-y-10 animate-in fade-in duration-700">
            {/* Real Stats Cards */}
            <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                <Card variant="outline" className="p-6 bg-white/[0.02] border-white/5 flex flex-col gap-3 hover:border-indigo-500/30 transition-all duration-500 group relative overflow-hidden">
                    <div className="absolute -right-4 -top-4 w-16 h-16 bg-indigo-500/10 blur-2xl rounded-full transition-all group-hover:scale-150" />
                    <div className="flex items-center justify-between relative">
                        <span className="text-[10px] font-black uppercase tracking-widest text-neutral-500">Ganancias Totales</span>
                        <div className="p-2 rounded-xl bg-indigo-500/10 text-indigo-400 group-hover:scale-110 transition-transform">
                            <TrendingUp size={16} />
                        </div>
                    </div>
                    <div className="space-y-1 relative">
                        <p className="text-3xl font-black italic tracking-tighter text-white tabular-nums">
                            {stats.total.toLocaleString("es-ES", { minimumFractionDigits: 2 })}€
                        </p>
                        <div className="flex items-center gap-1.5 text-[10px] font-bold text-emerald-400">
                            <ArrowUpRight size={12} />
                            <span>+12.5% vs mes anterior</span>
                        </div>
                    </div>
                </Card>

                <Card variant="outline" className="p-6 bg-white/[0.02] border-white/5 flex flex-col gap-3 hover:border-blue-500/30 transition-all duration-500 group relative overflow-hidden">
                    <div className="absolute -right-4 -top-4 w-16 h-16 bg-blue-500/10 blur-2xl rounded-full transition-all group-hover:scale-150" />
                    <div className="flex items-center justify-between relative">
                        <span className="text-[10px] font-black uppercase tracking-widest text-neutral-500">Activos Creados</span>
                        <div className="p-2 rounded-xl bg-blue-500/10 text-blue-400 group-hover:scale-110 transition-transform">
                            <Layers size={16} />
                        </div>
                    </div>
                    <div className="space-y-1 relative">
                        <p className="text-3xl font-black italic tracking-tighter text-white tabular-nums">{stats.count}</p>
                        <div className="flex items-center gap-1.5 text-[10px] font-bold text-blue-400">
                            <span>Sincronizados con KDP Engine</span>
                        </div>
                    </div>
                </Card>

                <Card variant="outline" className="p-6 bg-white/[0.02] border-white/5 flex flex-col gap-3 hover:border-emerald-500/30 transition-all duration-500 group relative overflow-hidden">
                    <div className="absolute -right-4 -top-4 w-16 h-16 bg-emerald-500/10 blur-2xl rounded-full transition-all group-hover:scale-150" />
                    <div className="flex items-center justify-between relative">
                        <span className="text-[10px] font-black uppercase tracking-widest text-neutral-500">CTR Promedio</span>
                        <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-400 group-hover:scale-110 transition-transform">
                            <Target size={16} />
                        </div>
                    </div>
                    <div className="space-y-1 relative">
                        <p className="text-3xl font-black italic tracking-tighter text-white tabular-nums">4.2%</p>
                        <div className="flex items-center gap-1.5 text-[10px] font-bold text-emerald-400 italic">
                            Altamente Optimizado
                        </div>
                    </div>
                </Card>

                <Card variant="outline" className="p-6 bg-white/[0.02] border-white/5 flex flex-col gap-3 hover:border-purple-500/30 transition-all duration-500 group relative overflow-hidden">
                    <div className="absolute -right-4 -top-4 w-16 h-16 bg-purple-500/10 blur-2xl rounded-full transition-all group-hover:scale-150" />
                    <div className="flex items-center justify-between relative">
                        <span className="text-[10px] font-black uppercase tracking-widest text-neutral-500">Efficiency</span>
                        <div className="p-2 rounded-xl bg-purple-500/10 text-purple-400 group-hover:scale-110 transition-transform">
                            <Zap size={16} />
                        </div>
                    </div>
                    <div className="space-y-1 relative">
                        <p className="text-3xl font-black italic tracking-tighter text-white tabular-nums">98%</p>
                        <div className="flex items-center gap-1.5 text-[10px] font-bold text-purple-400">
                            Auto-scaling habilitado
                        </div>
                    </div>
                </Card>
            </section>

            {/* Main Application Interface */}
            <section className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">

                {/* Product List - LEFT */}
                <div className="lg:col-span-7 space-y-6">
                    <div className="flex items-center justify-between px-2">
                        <div className="flex items-center gap-2">
                            <Box size={18} className="text-primary" />
                            <h2 className="text-xl font-bold tracking-tight text-white italic">Catálogo de Activos</h2>
                        </div>
                        <Badge variant="neutral" className="bg-white/5 border-white/10 text-[9px] font-black uppercase tracking-widest px-3">
                            {products.length} Archivos
                        </Badge>
                    </div>

                    <div className="space-y-4 max-h-[800px] overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-white/5">
                        {products.length === 0 ? (
                            <Card variant="outline" className="p-12 border-dashed border-white/10 bg-white/[0.01] flex flex-col items-center justify-center text-center space-y-4">
                                <div className="p-4 rounded-3xl bg-white/5 text-neutral-600">
                                    <Layers size={40} />
                                </div>
                                <div>
                                    <p className="text-lg font-bold text-white italic">No hay productos aún</p>
                                    <p className="text-sm text-neutral-500">Utiliza el panel de la derecha para crear tu primer activo digital.</p>
                                </div>
                            </Card>
                        ) : (
                            products.map((product) => (
                                <Card key={product.id} variant="glass" className="group relative p-6 border-white/5 bg-white/[0.01] hover:border-white/20 transition-all duration-300 overflow-hidden">
                                    <div className="absolute left-0 top-0 bottom-0 w-1 bg-gradient-to-b from-indigo-500 via-blue-500 to-cyan-500 opacity-30 group-hover:opacity-100 transition-opacity" />

                                    <div className="flex flex-col md:flex-row gap-6 relative">
                                        <div className="flex-1 space-y-4">
                                            <div className="flex items-start justify-between">
                                                <div>
                                                    <div className="flex items-center gap-2 mb-1">
                                                        <Badge variant="neutral" className="bg-indigo-500/10 border-indigo-500/20 text-indigo-400 text-[8px] font-black uppercase tracking-widest px-2">
                                                            {product.type}
                                                        </Badge>
                                                        <span className="text-[10px] font-medium text-neutral-600 font-mono">#{product.id.slice(-6)}</span>
                                                    </div>
                                                    <h3 className="text-xl font-black text-white italic tracking-tight">{product.title}</h3>
                                                </div>
                                                <Button
                                                    variant="ghost"
                                                    size="sm"
                                                    onClick={() => handleDeleteProduct(product.id)}
                                                    className="h-8 w-8 p-0 rounded-lg text-neutral-600 hover:text-rose-500 hover:bg-rose-500/10 transition-all"
                                                >
                                                    <Trash2 size={14} />
                                                </Button>
                                            </div>

                                            <p className="text-sm text-neutral-400 leading-relaxed max-w-lg mb-6">{product.description}</p>

                                            <div className="space-y-3">
                                                <h4 className="text-[9px] font-black uppercase tracking-widest text-neutral-500 flex items-center gap-2">
                                                    <Globe size={10} /> Distribución y Ventas
                                                </h4>
                                                <div className="flex flex-wrap gap-2">
                                                    {product.platforms.map((plat) => (
                                                        <div key={plat.name} className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-white/5 border border-white/5 hover:border-white/10 transition-colors">
                                                            <span className="text-[10px] font-bold text-neutral-400">{plat.name}</span>
                                                            <div className="w-1 h-3 bg-white/10 rounded-full" />
                                                            <span className="text-xs font-black italic tracking-tighter text-emerald-400 tabular-nums">
                                                                {plat.earnings.toFixed(2)}€
                                                            </span>
                                                        </div>
                                                    ))}
                                                </div>
                                            </div>
                                        </div>

                                        <div className="md:w-32 flex flex-col justify-between items-end gap-4 border-t md:border-t-0 md:border-l border-white/5 pt-4 md:pt-0 md:pl-6">
                                            <div className="text-right">
                                                <span className="text-[8px] font-black uppercase tracking-widest text-neutral-500 block">Total</span>
                                                <span className="text-2xl font-black italic tracking-tighter text-white tabular-nums">{product.totalEarnings.toFixed(2)}€</span>
                                            </div>
                                            <div className="flex items-center gap-1.5 text-neutral-600 text-[10px] font-bold italic">
                                                <CheckCircle2 size={12} className="text-emerald-500/50" />
                                                <span>Live</span>
                                            </div>
                                        </div>
                                    </div>
                                </Card>
                            ))
                        )}
                    </div>
                </div>

                {/* Create Form - RIGHT */}
                <div className="lg:col-span-5 space-y-6 sticky top-8">
                    <Card variant="glass" className="p-8 border-primary/20 bg-primary/5 space-y-8 shadow-[0_0_50px_rgba(25,113,255,0.05)]">
                        <div className="space-y-2">
                            <div className="flex items-center gap-2">
                                <Wand2 className="text-primary animate-pulse" size={20} />
                                <h2 className="text-xl font-bold tracking-tight text-white italic uppercase">Generador de Activos</h2>
                            </div>
                            <p className="text-xs text-neutral-400 font-medium">Define los parámetros básicos para el nuevo activo digital IA.</p>
                        </div>

                        <div className="space-y-6">
                            <div className="space-y-3">
                                <label className="text-[10px] font-black uppercase tracking-widest text-neutral-500 ml-1">Tipo de Activo Digital</label>
                                <div className="grid grid-cols-2 gap-3">
                                    {PRODUCT_TYPES.map((type) => (
                                        <button
                                            key={type.id}
                                            onClick={() => setSelectedType(type.id)}
                                            className={`flex flex-col items-center justify-center gap-3 p-4 rounded-2xl border transition-all duration-300 ${selectedType === type.id
                                                ? "bg-white/10 border-white/20 shadow-lg scale-[1.02]"
                                                : "bg-white/[0.02] border-white/5 opacity-60 hover:opacity-100"
                                                }`}
                                        >
                                            <div className={`p-2.5 rounded-xl ${type.bg} ${type.color}`}>
                                                {type.icon}
                                            </div>
                                            <span className="text-[10px] font-black uppercase tracking-tight text-center">{type.name}</span>
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <div className="space-y-2">
                                <label className="text-[10px] font-black uppercase tracking-widest text-neutral-500 ml-1">Título del Proyecto</label>
                                <input
                                    type="text"
                                    value={newTitle}
                                    onChange={(e) => setNewTitle(e.target.value)}
                                    placeholder="Ej: Minimalist Boho Patterns"
                                    className="w-full h-12 bg-white/5 border border-white/10 rounded-2xl px-5 text-sm text-white placeholder:text-neutral-600 focus:outline-none focus:border-primary/50 focus:bg-white/[0.08] transition-all"
                                />
                            </div>

                            <div className="space-y-2">
                                <label className="text-[10px] font-black uppercase tracking-widest text-neutral-500 ml-1">Descripción Estratégica</label>
                                <textarea
                                    value={newDesc}
                                    onChange={(e) => setNewDesc(e.target.value)}
                                    placeholder="Detalles sobre el nicho, estilo y público objetivo..."
                                    rows={3}
                                    className="w-full bg-white/5 border border-white/10 rounded-2xl p-5 text-sm text-white placeholder:text-neutral-600 focus:outline-none focus:border-primary/50 focus:bg-white/[0.08] transition-all resize-none"
                                />
                            </div>

                            <Button
                                onClick={handleAddProduct}
                                className="w-full h-14 bg-white text-black font-black uppercase tracking-widest text-[11px] rounded-2xl hover:bg-neutral-200 hover:scale-[1.02] active:scale-95 transition-all shadow-2xl shadow-indigo-500/10"
                            >
                                <Plus size={18} className="mr-2" /> Crear Activo Digital
                            </Button>
                        </div>

                        <div className="p-5 rounded-2xl bg-indigo-500/5 border border-indigo-500/10 space-y-3">
                            <p className="text-[9px] font-black text-indigo-400 uppercase tracking-widest flex items-center gap-2">
                                <AlertCircle size={10} /> Optimización IA activa
                            </p>
                            <p className="text-[11px] text-neutral-400 leading-relaxed italic">
                                Al crear el activo, el motor generará automáticamente metadatos SEO optimizados para Amazon KDP y Etsy basados en el título.
                            </p>
                        </div>
                    </Card>
                </div>
            </section>
        </div>
    );
}

// Reuse imports mentioned but might be needed
import { useRouter } from "next/navigation";
